a=input("Enter a string : ")
b=a.count("A")
c=a.count("E")
d=a.count("I")
e=a.count("O")
f=a.count("U")
g=a.count("a")
h=a.count("e")
i=a.count("i")
j=a.count("o")
k=a.count("u")
print(b+c+d+e+f+g+h+i+j+k)
